workflows:
  android-debug:
    name: Dalelminya Android APK
    max_build_duration: 60

    environment:
      java: 17

    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"

      - name: Check Gradle
        script: |
          gradle --version

      - name: Build Debug APK
        script: |
          gradle assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
